//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMgmt
{


    public partial class FolderAccess
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.ClientPeoplePicker ddlApprover;
        protected global::System.Web.UI.WebControls.Label L_ddlApprover;
        protected global::System.Web.UI.WebControls.Label WaitingApprover;
        protected global::System.Web.UI.WebControls.Label IsWaitingApprover;
        protected global::System.Web.UI.WebControls.Label L_WaitingApprover;
        /// <summary>
        /// Button1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        /// 
        protected global::System.Web.UI.WebControls.Panel panelMain;
        protected global::System.Web.UI.WebControls.Panel panelOld;

        protected global::System.Web.UI.WebControls.Button BSave;
        protected global::System.Web.UI.WebControls.Button BSubmit;
        protected global::System.Web.UI.WebControls.Button BBack;
        protected global::System.Web.UI.WebControls.Button BReject;
        protected global::System.Web.UI.WebControls.Button BLoadFolderDetails; 

        protected global::System.Web.UI.WebControls.Label Composer;
        protected global::System.Web.UI.WebControls.Label History;
        protected global::System.Web.UI.WebControls.Label Status;
        protected global::System.Web.UI.WebControls.Label L_Submitted;
        protected global::System.Web.UI.WebControls.Label L_Error;
        protected global::System.Web.UI.WebControls.Label L_Errors;
        protected global::System.Web.UI.WebControls.Label L_Serial;

        protected global::System.Web.UI.WebControls.DropDownList Building;
        protected global::System.Web.UI.WebControls.Literal L_Comments;
        protected global::System.Web.UI.WebControls.Label L_From;
        protected global::System.Web.UI.WebControls.Label L_Building;
        protected global::Telerik.Web.UI.RadTextBox Comments;

        protected global::System.Web.UI.WebControls.DropDownList FolderPrefix;
        protected global::System.Web.UI.WebControls.TextBox FolderPostfix;

        protected global::Telerik.Web.UI.RadGrid folderRights; // old 
        protected global::Telerik.Web.UI.RadGrid folderRightsV2;

        protected global::Microsoft.SharePoint.WebControls.ClientPeoplePicker Name_1;
        protected global::Telerik.Web.UI.RadTextBox AM_1;
        
        protected global::System.Web.UI.WebControls.TextBox From;
        
        protected global::System.Web.UI.WebControls.DropDownList AddRemove_1;
        protected global::System.Web.UI.WebControls.DropDownList Rights_1;
        protected global::System.Web.UI.WebControls.Label L_FolderGridErr;
        protected global::System.Web.UI.WebControls.Panel panelAdd;

        protected global::System.Web.UI.WebControls.Label L_Folder;
        protected global::System.Web.UI.WebControls.Label L_LoadFolderDetailsErr;
        protected global::System.Web.UI.WebControls.Label L_FolderChecked;
        protected global::System.Web.UI.WebControls.Label L_FolderOldRights;
        protected global::System.Web.UI.WebControls.Label FolderDiffs;

    }
}
