//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMgmt {

    using Telerik.Web.Design;
    using Telerik.Web.UI;
    using Microsoft.SharePoint;
    using Microsoft.SharePoint.WebControls; 

    public partial class MailAccess {

        /// <summary>
        /// TextBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>


        protected global::Microsoft.SharePoint.WebControls.ClientPeoplePicker ddlApprover;
        protected global::System.Web.UI.WebControls.Label L_ddlApprover;
        protected global::System.Web.UI.WebControls.Label WaitingApprover;
        protected global::System.Web.UI.WebControls.Label IsWaitingApprover;
        protected global::System.Web.UI.WebControls.Label L_WaitingApprover;
        /// <summary>
        /// Button1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        /// 
        protected global::System.Web.UI.WebControls.Panel panelMain;
        protected global::System.Web.UI.WebControls.Panel panelForwardToAdd;
        protected global::System.Web.UI.WebControls.Panel panelSendAsAdd;
        protected global::System.Web.UI.WebControls.Button BSave;
        protected global::System.Web.UI.WebControls.Button BSubmit;
        protected global::System.Web.UI.WebControls.Button BBack;
        protected global::System.Web.UI.WebControls.Button BReject;

        protected global::System.Web.UI.WebControls.Button BLoadMailDetails;
        protected global::System.Web.UI.WebControls.Label L_LoadMailDetailsErr;
        protected global::System.Web.UI.WebControls.Label Composer;
        protected global::System.Web.UI.WebControls.Label History;
        protected global::System.Web.UI.WebControls.Label Status;
        protected global::System.Web.UI.WebControls.Label  L_Error;
        protected global::System.Web.UI.WebControls.Label L_Errors;
        protected global::System.Web.UI.WebControls.Label L_Serial;
        protected global::System.Web.UI.WebControls.Label L_From;
        protected global::System.Web.UI.WebControls.TextBox From;
        protected global::System.Web.UI.WebControls.DropDownList Building;
        protected global::System.Web.UI.WebControls.TextBox DisplayName;
        protected global::System.Web.UI.WebControls.TextBox EMailAddressPrefix;
        protected global::System.Web.UI.WebControls.DropDownList EMailAddressPostfix;
        protected global::System.Web.UI.WebControls.TextBox MaxRecipients;
        protected global::Telerik.Web.UI.RadGrid ForwardTo;
        protected global::Telerik.Web.UI.RadGrid SendAs;
        protected global::System.Web.UI.WebControls.Label EMailAddressChecked;
        protected global::System.Web.UI.WebControls.Label EMailAddressDiffs;
        protected global::System.Web.UI.WebControls.Label EMailAddressOldForwardTo;
        protected global::System.Web.UI.WebControls.Label EMailAddressOldSendAs;
        protected global::System.Web.UI.WebControls.Label EMailAt; 
        //   protected global::Telerik.Web.UI.RadTextBox ForwardToAdd_1;
        protected global::Microsoft.SharePoint.WebControls.ClientPeoplePicker ForwardToAdd_1;
        protected global::Microsoft.SharePoint.WebControls.ClientPeoplePicker SendAsAdd_1;
  
        //protected global::Microsoft.SharePoint.WebControls.PeopleEditor SendAs;


        protected global::System.Web.UI.WebControls.Literal L_Comments;

        protected global::System.Web.UI.WebControls.Label L_Submitted;

        protected global::System.Web.UI.WebControls.Label L_Building;
        protected global::System.Web.UI.WebControls.Label L_DisplayName;
        protected global::System.Web.UI.WebControls.Label L_EMailAddress;
        protected global::System.Web.UI.WebControls.Label L_MaxRecipients;

        protected global::System.Web.UI.WebControls.Label L_ForwardToErr;
        protected global::System.Web.UI.WebControls.Label L_SendAsErr;

        protected global::Telerik.Web.UI.RadTextBox Comments;

    }
}
