//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMgmt {

    using Telerik.Web.Design;
    using Telerik.Web.UI; 
    public partial class SystemAccess {

        /// <summary>
        /// TextBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>

        protected global::Microsoft.SharePoint.WebControls.DateTimeControl EndDate;
        protected global::Microsoft.SharePoint.WebControls.PeopleEditor ddlApprover;
        /// <summary>
        /// Button1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panelMain;
        protected global::System.Web.UI.WebControls.Button BSave;
        protected global::System.Web.UI.WebControls.Button BSubmit;
        protected global::System.Web.UI.WebControls.Button BBack;
        protected global::System.Web.UI.WebControls.Button BReject;
        protected global::System.Web.UI.WebControls.Label IsWaitingApprover;
        protected global::System.Web.UI.WebControls.Label L_WaitingApprover;
        protected global::System.Web.UI.WebControls.Label Composer;
        protected global::System.Web.UI.WebControls.Label History;
        protected global::System.Web.UI.WebControls.Label Status;
        protected global::System.Web.UI.WebControls.Label  L_Error;
        protected global::System.Web.UI.WebControls.Label L_Errors;
        protected global::System.Web.UI.WebControls.Label L_Serial;
        protected global::System.Web.UI.WebControls.Label L_From;
        protected global::System.Web.UI.WebControls.TextBox From;

        protected global::System.Web.UI.WebControls.DropDownList Subject;
        protected global::System.Web.UI.WebControls.TextBox SubjectOther;
        protected global::System.Web.UI.WebControls.DropDownList Building;
        protected global::System.Web.UI.WebControls.TextBox AM;
        protected global::System.Web.UI.WebControls.TextBox Phone;
        protected global::System.Web.UI.WebControls.TextBox Name;
        protected global::System.Web.UI.WebControls.TextBox NameLatin;
        protected global::System.Web.UI.WebControls.TextBox Role;
        protected global::System.Web.UI.WebControls.TextBox Surname;
        protected global::System.Web.UI.WebControls.TextBox SurnameLatin;
        protected global::System.Web.UI.WebControls.TextBox T24TellerID;
        protected global::System.Web.UI.WebControls.TextBox T24Profile;
        protected global::System.Web.UI.WebControls.TextBox OSRole;
        protected global::System.Web.UI.WebControls.TextBox OSDep;
        protected global::System.Web.UI.WebControls.DropDownList OracleAccess;
        protected global::System.Web.UI.WebControls.TextBox ArotronRole;
        protected global::System.Web.UI.WebControls.TextBox ArotronGroup;
        protected global::System.Web.UI.WebControls.CheckBoxList Systems;
        protected global::System.Web.UI.WebControls.CheckBoxList BasicAccess;
        protected global::System.Web.UI.WebControls.Literal L_BasicAccess;
        protected global::System.Web.UI.WebControls.Literal L_Comments;
//         protected global::Telerik.Web.UI.RadDatePicker EndDate;

        protected global::System.Web.UI.WebControls.Label L_Submitted;
        protected global::System.Web.UI.WebControls.Label L_Subject;
        protected global::System.Web.UI.WebControls.Label L_SubjectOther;
        protected global::System.Web.UI.WebControls.Label L_Systems;

        protected global::System.Web.UI.WebControls.Label L_Building;
        protected global::System.Web.UI.WebControls.Label L_AM;
        protected global::System.Web.UI.WebControls.Label L_Phone;
        protected global::System.Web.UI.WebControls.Label L_Name;
        protected global::System.Web.UI.WebControls.Label L_NameLatin;
        protected global::System.Web.UI.WebControls.Label L_Role;
        protected global::System.Web.UI.WebControls.Label L_Surname;
        protected global::System.Web.UI.WebControls.Label L_SurnameLatin;
        protected global::System.Web.UI.WebControls.Label L_T24TellerID;
        protected global::System.Web.UI.WebControls.Label L_T24Profile;
        protected global::System.Web.UI.WebControls.Label L_OSRole;
        protected global::System.Web.UI.WebControls.Label L_OSDep;
        protected global::System.Web.UI.WebControls.Label L_OracleAccess;
        protected global::System.Web.UI.WebControls.Label L_ArotronRole;
        protected global::System.Web.UI.WebControls.Label L_ArotronGroup;
        protected global::System.Web.UI.WebControls.Label L_EndDate;
        protected global::System.Web.UI.WebControls.Label L_ddlApprover;

        protected global::System.Web.UI.WebControls.Panel panelT24;
        protected global::System.Web.UI.WebControls.Panel panelWindows;
        protected global::System.Web.UI.WebControls.Panel panelOracle;
        protected global::System.Web.UI.WebControls.Panel panelArotron;
        protected global::System.Web.UI.WebControls.Panel panelOS;

        protected global::Telerik.Web.UI.RadTextBox Comments;
    }
}
