//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetMgmt {

    using Telerik.Web.Design;
    using Telerik.Web.UI; 
    public partial class SystemAccess {

        /// <summary>
        /// TextBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>

        protected global::Microsoft.SharePoint.WebControls.DateTimeControl EndDate;
        protected global::Microsoft.SharePoint.WebControls.PeopleEditor ddlApprover;
        /// <summary>
        /// Button1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel panelMain;
        protected global::System.Web.UI.WebControls.Button BSave;
        protected global::System.Web.UI.WebControls.Button BSubmit;
        protected global::System.Web.UI.WebControls.Button BBack;
        protected global::System.Web.UI.WebControls.Button BReject;
        protected global::System.Web.UI.WebControls.Label IsWaitingApprover;
        protected global::System.Web.UI.WebControls.Label L_WaitingApprover;
        protected global::System.Web.UI.WebControls.Label Composer;
        protected global::System.Web.UI.WebControls.Label History;
        protected global::System.Web.UI.WebControls.Label Status;
        protected global::System.Web.UI.WebControls.Label  L_Error;
        protected global::System.Web.UI.WebControls.Label L_Errors;
        protected global::System.Web.UI.WebControls.Label L_Serial;
        protected global::System.Web.UI.WebControls.Label L_From;
        protected global::System.Web.UI.WebControls.TextBox From;

        protected global::System.Web.UI.WebControls.DropDownList Subject;
        protected global::System.Web.UI.WebControls.TextBox SubjectOther;
        protected global::System.Web.UI.WebControls.DropDownList Building;
        protected global::System.Web.UI.WebControls.DropDownList DocumentManagementLibrary;
        protected global::System.Web.UI.WebControls.TextBox AM;
        protected global::System.Web.UI.WebControls.TextBox Phone;
        protected global::System.Web.UI.WebControls.TextBox Name;
        protected global::System.Web.UI.WebControls.TextBox NameLatin;
        protected global::System.Web.UI.WebControls.TextBox Role;
        protected global::System.Web.UI.WebControls.TextBox Surname;
        protected global::System.Web.UI.WebControls.TextBox SurnameLatin;
        protected global::System.Web.UI.WebControls.TextBox T24TellerID;
        protected global::System.Web.UI.WebControls.TextBox T24Profile;
        protected global::System.Web.UI.WebControls.TextBox OSRole;
        protected global::System.Web.UI.WebControls.TextBox OSDep;
        protected global::System.Web.UI.WebControls.DropDownList G4Access;
        protected global::System.Web.UI.WebControls.DropDownList _3DSecureAccess;
        protected global::System.Web.UI.WebControls.DropDownList OracleAccess;
        protected global::System.Web.UI.WebControls.DropDownList OMNIAAccess;
        protected global::System.Web.UI.WebControls.TextBox ArotronRole;
        protected global::System.Web.UI.WebControls.TextBox ArotronGroup;
        protected global::System.Web.UI.WebControls.CheckBoxList Systems;
        protected global::System.Web.UI.WebControls.CheckBoxList BasicAccess;
        
        protected global::System.Web.UI.WebControls.Literal L_BasicAccess;
        protected global::System.Web.UI.WebControls.Literal L_Comments;
//         protected global::Telerik.Web.UI.RadDatePicker EndDate;

        protected global::System.Web.UI.WebControls.Label L_Submitted;
        protected global::System.Web.UI.WebControls.Label L_Subject;
        protected global::System.Web.UI.WebControls.Label L_SubjectOther;
        protected global::System.Web.UI.WebControls.Label L_Systems;

        protected global::System.Web.UI.WebControls.Label L_Building;
        protected global::System.Web.UI.WebControls.Label L_AM;
        protected global::System.Web.UI.WebControls.Label L_Phone;
        protected global::System.Web.UI.WebControls.Label L_Name;
        protected global::System.Web.UI.WebControls.Label L_NameLatin;
        protected global::System.Web.UI.WebControls.Label L_Role;
        protected global::System.Web.UI.WebControls.Label L_Surname;
        protected global::System.Web.UI.WebControls.Label L_SurnameLatin;
        protected global::System.Web.UI.WebControls.Label L_T24TellerID;
        protected global::System.Web.UI.WebControls.Label L_T24Profile;
        protected global::System.Web.UI.WebControls.Label L_OSRole;
        protected global::System.Web.UI.WebControls.Label L_OSDep;
        protected global::System.Web.UI.WebControls.Label L_G4Access;
        protected global::System.Web.UI.WebControls.Label L_3DSecureAccess;
        protected global::System.Web.UI.WebControls.Label L_DocumentManagementLibrary;
        protected global::System.Web.UI.WebControls.Label L_OracleAccess;
        protected global::System.Web.UI.WebControls.Label L_OMNIAAccess;
        protected global::System.Web.UI.WebControls.Label L_ArotronRole;
        protected global::System.Web.UI.WebControls.Label L_ArotronGroup;
        protected global::System.Web.UI.WebControls.Label L_EndDate;
        protected global::System.Web.UI.WebControls.Label L_ddlApprover;
       


        protected global::System.Web.UI.WebControls.Panel panelT24;
        protected global::System.Web.UI.WebControls.Panel panelWindows;
        protected global::System.Web.UI.WebControls.Panel panelG4;
        protected global::System.Web.UI.WebControls.Panel panel3DSecure;
        protected global::System.Web.UI.WebControls.Panel panelOracle;
        protected global::System.Web.UI.WebControls.Panel panelOMNIA;
        protected global::System.Web.UI.WebControls.Panel panelArotron;
        protected global::System.Web.UI.WebControls.Panel panelOS;
        protected global::System.Web.UI.WebControls.Panel panelMOTIVIAN;
        protected global::System.Web.UI.WebControls.Panel panelFACTORING;
        protected global::System.Web.UI.WebControls.Panel panelNEWTON;
        protected global::System.Web.UI.WebControls.Panel panelNEWTONMutual;
        protected global::System.Web.UI.WebControls.Panel panelImportExport;
        protected global::System.Web.UI.WebControls.Panel panelSWIFT;
        protected global::System.Web.UI.WebControls.Panel panelAssesments;
        protected global::System.Web.UI.WebControls.Panel panelFCMAML;
        protected global::System.Web.UI.WebControls.Panel panelSASAML;
        protected global::System.Web.UI.WebControls.Panel panelRegTekAML;
        protected global::System.Web.UI.WebControls.Panel panelDocumentManagement;
        protected global::System.Web.UI.WebControls.Panel panelLeasing;
        protected global::System.Web.UI.WebControls.Panel panelEthicsCode;
        protected global::System.Web.UI.WebControls.Panel panelBankAttachments;
        protected global::System.Web.UI.WebControls.Panel panelSCANHRMS;
        protected global::System.Web.UI.WebControls.Panel panelSpring;
        protected global::System.Web.UI.WebControls.Panel panelCCR;
        protected global::System.Web.UI.WebControls.Panel panelCode;
        protected global::System.Web.UI.WebControls.Panel panelQUANTUMFIS;
        protected global::System.Web.UI.WebControls.Panel panelBPMDIGITAL1;
        protected global::System.Web.UI.WebControls.Panel panelBPMLOSSMECorporate;
        protected global::System.Web.UI.WebControls.Panel panelBPMLOSConsume;
        protected global::System.Web.UI.WebControls.Panel panelACSWebsite;
        protected global::System.Web.UI.WebControls.Panel panelACSConnectWebsite;


        protected global::System.Web.UI.WebControls.DropDownList NEWTONAccess;
        protected global::System.Web.UI.WebControls.DropDownList NEWTONMutualAccess;
        protected global::System.Web.UI.WebControls.DropDownList ImportExportAccess;
        protected global::System.Web.UI.WebControls.DropDownList SWIFTAccess;
        protected global::System.Web.UI.WebControls.DropDownList AssesmentsAccess;
        protected global::System.Web.UI.WebControls.DropDownList FCMAMLAccess;
        protected global::System.Web.UI.WebControls.DropDownList SASAMLAccess;
        protected global::System.Web.UI.WebControls.DropDownList RegTekAMLAccess;
        protected global::System.Web.UI.WebControls.DropDownList MOTIVIANAccess;
        protected global::System.Web.UI.WebControls.DropDownList FACTORINGAccess;
        protected global::System.Web.UI.WebControls.DropDownList LeasingAccess;
        protected global::System.Web.UI.WebControls.DropDownList EthicsCodeAccess;
        protected global::System.Web.UI.WebControls.DropDownList BankAttachmentsAccess;
        protected global::System.Web.UI.WebControls.DropDownList SCANHRMSAccess;
        protected global::System.Web.UI.WebControls.DropDownList SpringAccess;
        protected global::System.Web.UI.WebControls.DropDownList QUANTUMFISAccess;
        protected global::System.Web.UI.WebControls.DropDownList CCRAccess;
        protected global::System.Web.UI.WebControls.DropDownList CodeAccess;
        protected global::System.Web.UI.WebControls.DropDownList DM_LMD_Customers;
        protected global::System.Web.UI.WebControls.DropDownList DM_IMPEX;
        protected global::System.Web.UI.WebControls.DropDownList DM_DANEIA;
        protected global::System.Web.UI.WebControls.DropDownList DM_BOA_AITISEIS;
        protected global::System.Web.UI.WebControls.DropDownList DM_BOA;
        protected global::System.Web.UI.WebControls.DropDownList DM_BOA_ML_LIB;
        protected global::System.Web.UI.WebControls.DropDownList DM_BOA_HR_LIB;
        protected global::System.Web.UI.WebControls.DropDownList DM_BOA_LEGAL_LIB;
        protected global::System.Web.UI.WebControls.DropDownList DM_XORHGHSEIS;
        protected global::System.Web.UI.WebControls.TextBox DM_Branch;
        protected global::System.Web.UI.WebControls.DropDownList BPMDIGITAL1Access;
        protected global::System.Web.UI.WebControls.DropDownList BPMLOSSMECorporateAccess;
        protected global::System.Web.UI.WebControls.DropDownList BPMLOSConsumeAccess;
        protected global::System.Web.UI.WebControls.DropDownList ACSWebsiteAccess;
        protected global::System.Web.UI.WebControls.DropDownList ACSConnectWebsiteAccess;


        protected global::System.Web.UI.WebControls.Label L_NEWTONAccess;
        protected global::System.Web.UI.WebControls.Label L_NEWTONMutualAccess;
        protected global::System.Web.UI.WebControls.Label L_ImportExportAccess;
        protected global::System.Web.UI.WebControls.Label L_SWIFTAccess;
        protected global::System.Web.UI.WebControls.Label L_AssesmentsAccess;
        protected global::System.Web.UI.WebControls.Label L_FCMAMLAccess;
        protected global::System.Web.UI.WebControls.Label L_SASAMLAccess;
        protected global::System.Web.UI.WebControls.Label L_RegTekAMLAccess;
        protected global::System.Web.UI.WebControls.Label L_MOTIVIANAccess;
        protected global::System.Web.UI.WebControls.Label L_FACTORINGAccess;
        protected global::System.Web.UI.WebControls.Label L_LeasingAccess;
        protected global::System.Web.UI.WebControls.Label L_EthicsCodeAccess;
        protected global::System.Web.UI.WebControls.Label L_BankAttachmentsAccess;
        protected global::System.Web.UI.WebControls.Label L_SCANHRMSAccess;
        protected global::System.Web.UI.WebControls.Label L_SpringAccess;
        protected global::System.Web.UI.WebControls.Label L_CCRAccess;
        protected global::System.Web.UI.WebControls.Label L_QUANTUMFISAccess;
        protected global::System.Web.UI.WebControls.Label L_CodeAccess;
        protected global::System.Web.UI.WebControls.Label L_DM_LMD_Customers;
        protected global::System.Web.UI.WebControls.Label L_DM_IMPEX;
        protected global::System.Web.UI.WebControls.Label L_DM_DANEIA;
        protected global::System.Web.UI.WebControls.Label L_DM_BOA_AITISEIS;
        protected global::System.Web.UI.WebControls.Label L_DM_BOA;
        protected global::System.Web.UI.WebControls.Label L_DM_BOA_ML_LIB;
        protected global::System.Web.UI.WebControls.Label L_DM_BOA_HR_LIB;
        protected global::System.Web.UI.WebControls.Label L_DM_BOA_LEGAL_LIB;
        protected global::System.Web.UI.WebControls.Label L_DM_XORHGHSEIS;
        protected global::System.Web.UI.WebControls.Label L_DM_Branch;
        protected global::System.Web.UI.WebControls.Label L_BPMDIGITAL1Access;
        protected global::System.Web.UI.WebControls.Label L_BPMLOSSMECorporateAccess;
        protected global::System.Web.UI.WebControls.Label L_BPMLOSConsumeAccess;
        protected global::System.Web.UI.WebControls.Label L_ACSWebsiteAccess;
        protected global::System.Web.UI.WebControls.Label L_ACSConnectWebsiteAccess;



        protected global::Telerik.Web.UI.RadTextBox Comments;

     


    }
}
